In [1]:
import pandas as pd
df = pd.read_csv('Sample - Superstore.csv', encoding='latin-1')
df.shape

(9994, 21)

In [2]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [4]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Order Date'].dt.year

0       2016
1       2016
2       2016
3       2015
4       2015
        ...
9989    2014
9990    2017
9991    2017
9992    2017
9993    2017
Name: Order Date, Length: 9994, dtype: int32

In [5]:
df['Year'] = df['Order Date'].dt.year

In [6]:
df.groupby('Category')['Sales'].sum()

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [7]:
df.groupby('Sub-Category')['Profit'].sum().sort_values()

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5546.2540
Art             6527.7870
Envelopes       6964.1767
Furnishings    13059.1436
Appliances     18138.0054
Storage        21278.8264
Chairs         26590.1663
Binders        30221.7633
Paper          34053.5693
Accessories    41936.6357
Phones         44515.7306
Copiers        55617.8249
Name: Profit, dtype: float64

In [8]:
df['Sales']

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9994, dtype: float64

In [9]:
df[['Sales', 'Profit']]

         Sales    Profit
0     261.9600   41.9136
1     731.9400  219.5820
2      14.6200    6.8714
3     957.5775 -383.0310
4      22.3680    2.5164
...        ...       ...
9989   25.2480    4.1028
9990   91.9600   15.6332
9991  258.5760   19.3932
9992   29.6000   13.3200
9993  243.1600   72.9480

[9994 rows x 2 columns]

In [10]:
df['Sales'] > 1000

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Sales, Length: 9994, dtype: bool

In [11]:
df[df['Sales'] > 1000].shape

(468, 22)

In [12]:
mask = df['Sales'] > 1000
mask

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Sales, Length: 9994, dtype: bool

In [13]:
df[mask]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year
10,11,CA-2014-115812,2014-06-09,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092,2014
24,25,CA-2015-106320,2015-09-25,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649,2015
27,28,US-2015-150630,2015-09-17,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522,2015
35,36,CA-2016-117590,2016-12-08,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737,2016
54,55,CA-2016-105816,2016-12-11,12/17/2016,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,9867,US-2015-116981,2015-03-26,3/28/2015,Second Class,SM-20950,Suzanne McNair,Corporate,United States,New York City,...,East,OFF-ST-10002615,Office Supplies,Storage,"Dual Level, Single-Width Filing Carts",1085.420,7,0.0,282.2092,2015
9925,9926,CA-2015-159534,2015-03-20,3/23/2015,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.936,8,0.2,353.5792,2015
9929,9930,CA-2016-129630,2016-09-04,9/4/2016,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865,2016
9947,9948,CA-2017-121559,2017-06-01,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464,2017
9948,9949,CA-2017-121559,2017-06-01,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160,2017

In [14]:
df[(df['Sales'] > 1000) & (df['Profit'] < 0)].shape

(78, 22)

In [15]:
df[['Sales','Profit']].sum()

Sales     2.297201e+06
Profit    2.863970e+05
dtype: float64

In [16]:
df[['Sales','Profit']].sum().round(0)

Sales     2297201.0
Profit     286397.0
dtype: float64

In [17]:
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [18]:
df.groupby('Category')[['Sales','Profit']].sum()

                       Sales       Profit
Category
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008
Technology       836154.0330  145454.9481

In [19]:
df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [20]:
region = df.groupby('Region')[['Sales','Profit']].sum()
region['Margin %'] = (region['Profit'] / region['Sales'] * 100).round(1)
region.sort_values('Margin %')

               Sales       Profit  Margin %
Region
Central  501239.8908   39706.3625       7.9
South    391721.9050   46749.4303      11.9
East     678781.2400   91522.7800      13.5
West     725457.8245  108418.4489      14.9

In [21]:
df.groupby('Year')[['Sales','Profit']].sum()

            Sales      Profit
Year
2014  484247.4981  49543.9741
2015  470532.5090  61618.6037
2016  609205.5980  81795.1743
2017  733215.2552  93439.2696

In [22]:
yearly = df.groupby('Year')[['Sales','Profit']].sum()
yearly['Sales YoY %'] = (yearly['Sales'].pct_change() * 100).round(1)
yearly

            Sales      Profit  Sales YoY %
Year
2014  484247.4981  49543.9741          NaN
2015  470532.5090  61618.6037         -2.8
2016  609205.5980  81795.1743         29.5
2017  733215.2552  93439.2696         20.4

In [23]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [24]:
df['Ship Mode'].value_counts(normalize=True) * 100

Ship Mode
Standard Class    59.715829
Second Class      19.461677
First Class       15.389234
Same Day           5.433260
Name: proportion, dtype: float64

In [25]:
pd.crosstab(df['Ship Mode'], df['Segment'], normalize='columns') * 100

Segment          Consumer  Corporate  Home Office
Ship Mode
First Class     14.814101  16.059603    15.928211
Same Day         6.106723   3.774834     6.281548
Second Class    19.649393  20.165563    17.722939
Standard Class  59.429782  60.000000    60.067302

In [26]:
disc = df.groupby('Sub-Category').agg(
    AvgDiscount=('Discount','mean'),
    TotalProfit=('Profit','sum')
)
disc.sort_values('AvgDiscount', ascending=False)

              AvgDiscount  TotalProfit
Sub-Category
Binders          0.372292   30221.7633
Machines         0.306087    3384.7569
Tables           0.261285  -17725.4811
Bookcases        0.211140   -3472.5560
Chairs           0.170178   26590.1663
Appliances       0.166524   18138.0054
Copiers          0.161765   55617.8249
Phones           0.154556   44515.7306
Furnishings      0.138349   13059.1436
Fasteners        0.082028     949.5182
Envelopes        0.080315    6964.1767
Accessories      0.078452   41936.6357
Supplies         0.076842   -1189.0995
Paper            0.074891   34053.5693
Art              0.074874    6527.7870
Storage          0.074704   21278.8264
Labels           0.068681    5546.2540

In [27]:
df.groupby('Discount').agg(
    Lines=('Profit','size'),
    AvgProfit=('Profit','mean')
)

          Lines   AvgProfit
Discount
0.00       4798   66.900292
0.10         94   96.055074
0.15         52   27.288298
0.20       3657   24.702572
0.30        227  -45.679636
0.32         27  -88.560656
0.40        206 -111.927429
0.45         11 -226.646464
0.50         66 -310.703456
0.60        138  -43.077212
0.70        418  -95.874060
0.80        300 -101.796797

In [28]:
top_sales  = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)
top_profit = df.groupby('Product Name')['Profit'].sum().sort_values(ascending=False).head(10)

In [29]:
top_sales

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [30]:
top_profit

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

In [31]:
profit_by_product = df.groupby('Product Name')['Profit'].sum().round(2)
profit_by_product.loc[top_sales.index]

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.93
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.04
Cisco TelePresence System EX90 Videoconferencing Unit                          -1811.08
HON 5400 Series Task Chairs for Big and Tall                                       0.00
GBC DocuBind TL300 Electric Binding System                                      2233.51
GBC Ibimaster 500 Manual ProClick Binding System                                 760.98
Hewlett Packard LaserJet 3310 Copier                                            6983.88
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.98
GBC DocuBind P400 Electric Binding System                                      -1878.17
High Speed Automatic Electric Letter Opener                                     -262.00
Name: Profit, dtype: float64

In [32]:
df.groupby('State')['Profit'].sum().sort_values().head(5)

State
Texas            -25729.3563
Ohio             -16971.3766
Pennsylvania     -15559.9603
Illinois         -12607.8870
North Carolina    -7490.9122
Name: Profit, dtype: float64

In [33]:
tx = df[df['State'] == 'Texas']

In [34]:
tx

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year
14,15,US-2015-118983,2015-11-22,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580,2015
15,16,US-2015-118983,2015-11-22,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160,2015
34,35,CA-2017-107727,2017-10-19,10/23/2017,Second Class,MA-17560,Matt Abelman,Home Office,United States,Houston,...,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.4720,3,0.20,9.9468,2017
35,36,CA-2016-117590,2016-12-08,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.5440,7,0.20,123.4737,2016
36,37,CA-2016-117590,2016-12-08,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,5,0.60,-147.9630,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9919,9920,CA-2016-149272,2016-03-15,3/19/2016,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,528.4300,5,0.30,-143.4310,2016
9920,9921,CA-2016-149272,2016-03-15,3/19/2016,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,Central,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.3860,7,0.80,-35.8176,2016
9961,9962,CA-2015-168088,2015-03-19,3/22/2015,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,Central,OFF-PA-10000675,Office Supplies,Paper,Xerox 1919,65.5840,2,0.20,23.7742,2015
9962,9963,CA-2015-168088,2015-03-19,3/22/2015,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704,2015
9972,9973,CA-2016-130225,2016-09-11,9/17/2016,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Houston,...,Central,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,99.5680,2,0.20,33.6042,2016

In [35]:
tx['Discount'].mean()

np.float64(0.3701928934010153)

In [36]:
tx.groupby('Discount').agg(Lines=('Profit','size'), Profit=('Profit','sum'))

          Lines      Profit
Discount
0.20        570   8225.9253
0.30         94  -4732.3256
0.32         27  -2391.1377
0.40         13  -2666.8434
0.60         81  -3312.6786
0.80        200 -20852.2963